#ifndef MY_SOUNDS_H
#define MY_SOUNDS_H

#define FREQ_BUTTON 440
#define FREQ_BACK_BUTTON  523
#define FREQ_JOYSTICK 587

#define FREQ_BULLET 392
#define FREQ_POWER_UP_PICKUP 880
#define FREQ_TAKE_DAMAGE 369

#define NUMBER_OF_END_NOTES 3

#define FREQ_END_FIRST_NOTE 739
#define FREQ_END_SECOND_NOTE 783
#define FREQ_END_THIRD_NOTE 880

#define TIME_OF_NOTE 200
#define TIME_BETWEEN_NOTES 100

#define SECOND_NOTE_IDX 2

#define DEFAULT_SOUND_DURATION 100

#endif